version: 2

dockers:
  - image_templates:
      - "fugginold/dockwatch:{{ .Tag }}-amd64"
    dockerfile: Dockerfile
    use: buildx
    goos: linux
    goarch: amd64

  - image_templates:
      - "fugginold/dockwatch:{{ .Tag }}-arm64"
    dockerfile: Dockerfile
    use: buildx
    goos: linux
    goarch: arm64

registries:
  - name: dockerhub
    url: https://index.docker.io/v1/
    username: ${{ secrets.DOCKERHUB_USERNAME }}
    password: ${{ secrets.DOCKERHUB_TOKEN }}

docker_manifests:
  - name_template: "fugginold/dockwatch:{{ .Tag }}"
    image_templates:
      - "fugginold/dockwatch:{{ .Tag }}-amd64"
      - "fugginold/dockwatch:{{ .Tag }}-arm64"

  - name_template: "fugginold/dockwatch:latest"
    image_templates:
      - "fugginold/dockwatch:{{ .Tag }}-amd64"
      - "fugginold/dockwatch:{{ .Tag }}-arm64"

  - name_template: "fugginold/dockwatch:stable"
    image_templates:
      - "fugginold/dockwatch:{{ .Tag }}-amd64"
      - "fugginold/dockwatch:{{ .Tag }}-arm64"
release:
  draft: false
  prerelease: false
  # Remove the next line if you want to auto-generate release notes
  # note: ""
