version: 2

project_name: dockwatch

before:
  hooks:
    - go mod tidy

builds:
  - id: dockwatch
    main: .
    binary: dockwatch
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

dockers:
  - image_templates:
      - "fugginold/dockwatch:{{ .Tag }}"
      - "fugginold/dockwatch:latest"
      - "fugginold/dockwatch:stable"
    dockerfile: Dockerfile
    use: buildx
    goos: linux
    goarch:
      - amd64
      - arm64

release:
  prerelease: auto
  github:
    owner: FugginOld
    name: dockwatch

changelog:
  use: github
