version: '3.7'

services:
  dockwatch:
    container_name: dockwatch
    build:
      context: ./
      dockerfile: dockerfiles/Dockerfile.dev-self-contained
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - dockwatch-config:/config
    ports:
      - 8080:8080
    command: --interval 10 --http-api-token demotoken --debug parent child
  parent:
    image: nginx
    container_name: parent
  child:
    image: nginx:alpine
    labels:
      com.centurylinklabs.dockwatch.depends-on: parent
    container_name: child

volumes:
  dockwatch-config: {}
